#! /bin/sh
#
# Some servers (like Savannah) refuse to force-update branches. This script
# can be used to workaround that.
# The branch is first deleted and push back.

if [[ "$1" = "" ]]; then
   echo git fpush branch_name;
   exit 1;
fi

git push origin :$1 && git push origin $1
