#! /bin/sh
#
# Some servers (like Savannah) refuse to force-update branches. This script
# can be used to workaround that.
# The branch is first deleted and push back.

branch=$1

if [ "$1" = "" ]; then
   # Use current branch
   branch=`git branch | egrep '^\* ' | cut -f2 -d' '`
fi

git push origin :$branch && git push origin $branch
