#! /bin/sh

# Look for the Git root directory
ROOT=`pwd`
while [ ! "$ROOT" = "" -a ! -d $ROOT/.git ]; do
   cd ..
   ROOT=`pwd`
done

if [ ! -f .git/config ]; then
   echo Must be run inside a Git repository
fi;

FS=" ="
svnrepo=`git svn info | grep URL | cut -f2 -d' '`
echo Looking for empty directories from $svnrepo

FILE=/tmp/files-$$

svn list -R $svnrepo > $FILE

while read entry
do
   if [ "${entry: -1:1}" == "/" ]; then
      if [ ! -d "$entry" ]; then
      	 echo create $entry
	 mkdir -p $entry
      fi
   fi
done < $FILE

rm -f $FILE
