#! /bin/sh

program=$0

USAGE='[--stat]'

LONG_USAGE="   Read wip file and display topic branch/log waiting for merging

   The WIP file is '.git/.wip'. There is three kinds of line:

      <empty>               : does nothing
      --- <text>            : display --- <text> as-is
      branch [branch-point] : output commits done on branch since branch-point
                              Default value for branch-point is master.
"

exec_path=$(git --exec-path)
. $exec_path/git-sh-setup
require_work_tree
cd_to_toplevel

FILE=".git/.wip"
STAT=0

display () {
   branch=$1
   from=${2:-master}
   n=$(git cherry $from $branch | wc -l)
   echo
   printf "  * $branch (`git log -1 --pretty="%ai" $branch`)"
   if [ "$n" = "" ]; then
       echo ""
   elif [ "$n" = "1" ]; then
       echo " 1 commit"
   else
       echo " $n commits"
   fi
   git log --pretty="      %s" $branch ^$from |
       while read line; do printf -- "   - %s\n" "$line"; done
   if [ "$STAT" = "1" ]; then
       echo ""
       git diff $branch~$n..$branch --stat | sed 's,^,    ,g'
   fi
}

handle_line () {
   line="$1"
   first=$2

   case "$first" in
      "")    ;;
      "---") echo; echo "$line";
             ;;
      *)     display $first $3;
   esac
}

while :
do
    case $1 in
	-h|*help)
	    usage
	    ;;
	--stat)
	    STAT=1
	    ;;
	*)
	    if [ -f $FILE ]; then
		while read line; do handle_line "$line" $line; done < $FILE;
	    else
		echo No WIP description for this project.
	    fi
	    break
	    ;;
    esac
    shift
done
