#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, make this file executable by "chmod +x post-update".

# exec git-update-server-info

. /home/git/scripts/git-hook-support.sh

trac_post_commit_record_log gtest
