#!/bin/sh

GNATROOT=/opt/gnat/2007

PATH=$GNATROOT/bin:$PATH

res=0

function check() {
   id=$4
   file=`basename $6`
   git show $id > /tmp/$file
   ( cd /tmp; style_checker $file; )
   res=$(($res + $?))
   rm -f /tmp/$file
}

# Get files to be commited
# <N1> <N2> <Id-OLD> <Id-NEW> <status> <Filename>
git-diff-index -M --cached HEAD > /tmp/files

while read list
do
   check $list
done < /tmp/files

rm /tmp/files

exit $res
